development/django_test_project/depot/depot/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from depot.views import hello

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'depot.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^hello/$', hello),
    url(r'^admin/', include(admin.site.urls)),
)

development/django_test_project/django_mysite/demo_app/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from demo_app import views

urlpatterns = patterns('',
	url(r'^$', TemplateView.as_view(template_name='index.html'), name="home"),
    url(r'^contact$', TemplateView.as_view(template_name='contact.html'), name="contact"),
    url(r'^form$', views.demo_form, name="demo_form"),
    url(r'^form_template$', views.demo_form_with_template, name="demo_form_with_template"),
    url(r'^form_inline$', views.demo_form_inline, name="demo_form_inline"),
    url(r'^formset$', views.demo_formset, {}, name="demo_formset"),
    url(r'^tabs$', views.demo_tabs, {}, name="demo_tabs"),
    url(r'^pagination$', views.demo_pagination, {}, name="demo_pagination"),
    url(r'^widgets$', views.demo_widgets, {}, name="demo_widgets"),
    url(r'^buttons$', TemplateView.as_view(template_name='buttons.html'), name="buttons"),
    url(r'^example$', TemplateView.as_view(template_name='base.html.example'), name="example"),
    #url(r'^example$', views.example, name="example"),
)

development/django_test_project/django_mysite/django_mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

from django.views.generic import TemplateView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'django_mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),

    # bootstrap toolkit
    url(r'^bootstrap/', include('demo_app.urls', namespace="demo_app")),

    # blog
    url(r'^blog/', include('blog.urls', namespace="blog")),

)


if settings.DEBUG:
    urlpatterns += patterns('',
            url(r'^media/(?P<path>.*)$', "django.views.static.serve",  {"document_root": settings.MEDIA_ROOT,}),
)

development/django_test_project/mysite/contact/urls.py
#from django.conf.urls.defaults import *
from django.conf.urls import patterns, url, include
from mysite.contant import views

urlpatterns = patterns('',
	(r'^foo/$', views.foobar_view, {'template_name': 'template1.html'}),
	(r'^bar/$', views.foobar_view, {'template_name': 'template2.html'}),
	)

urlpatterns =+ patterns('',
	(r'^events/$',views.object_list, {'model': models.Event}),
	(r'^blog/entries/$', views.object_list, {'model': models.BlogEntry}),
	)

development/django_test_project/mysite/urls.py
#from django.conf.urls.defaults import *
from django.conf.urls import patterns, url, include
from django.conf import settings
from mysite import views
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('mysite.views',
    (r'^hello/$','hello'),
    #('^/$', my_homepage_view),
    (r'^time/$', 'current_datetime'),
    (r'^time/plus/(\d{1,2})/$','hours_ahead'),
    #(r'^request/$',display_meta),
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^books/',include('mysite.books.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

#if settings.DEBUG:
#    urlpatterns += patterns('',
#        (r'^debuginfo/$',views.debug),
#        )

development/django_test_project/django_mysite/demo_app/forms.py
from django import forms
from django.contrib.auth.models import User
from bootstrap_toolkit.widgets import BootstrapDateInput, BootstrapTextInput, BootstrapUneditableInput

class TestForm(forms.Form):
    date = forms.DateField(
        widget=BootstrapDateInput(),
    )
    title = forms.CharField(
        max_length=100,
        help_text=u'This is the standard text input',
    )
    body = forms.CharField(
        max_length=100,
        help_text=u'This is a text area',
        widget=forms.Textarea(
            attrs={
                'title': 'I am "nice"',
            }
        ),
    )
    disabled = forms.CharField(
        max_length=100,
        required=False,
        help_text=u'I am disabled',
        widget=forms.TextInput(attrs={
            'disabled': 'disabled',
            'placeholder': 'I am disabled',
        })
    )
    uneditable = forms.CharField(
        max_length=100,
        help_text=u'I am uneditable and you cannot enable me with JS',
        initial=u'Uneditable',
        widget=BootstrapUneditableInput()
    )
    content = forms.ChoiceField(
        choices=(
            ("text", "Plain text"),
            ("html", "HTML"),
        ),
        help_text=u'Pick your choice',
    )
    email = forms.EmailField()
    like = forms.BooleanField(required=False)
    fruits = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=(
            ("apple", "Apple"),
            ("pear", "Pear"),
        ),
        help_text=u'As you can see, multiple checkboxes work too',
    )
    number = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={
            'inline': True,
        }),
        choices=(
            ("3", "Three"),
            ("33", "Thirty three"),
            ("333", "Three hundred thirty three"),
        ),
        help_text=u'And can be inline',
    )
    color = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'data-demo-attr': 'bazinga'}),
        choices=(
            ("#f00", "red"),
            ("#0f0", "green"),
            ("#00f", "blue"),
        ),
        help_text=u'And we have <i>radiosets</i>',
    )
    prepended = forms.CharField(
        max_length=100,
        help_text=u'I am prepended by a P',
        widget=BootstrapTextInput(prepend='P'),
    )

    def clean(self):
        cleaned_data = super(TestForm, self).clean()
        raise forms.ValidationError("This error was added to show the non field errors styling.")
        return cleaned_data


class TestModelForm(forms.ModelForm):
    class Meta:
        model = User


class TestInlineForm(forms.Form):
    query = forms.CharField(required=False, label="")
    vegetable = forms.ChoiceField(
        choices=(
            ("broccoli", "Broccoli"),
            ("carrots", "Carrots"),
            ("turnips", "Turnips"),
        ),
    )
    active = forms.ChoiceField(widget=forms.RadioSelect, label="", choices=(
        ('all', 'all'),
        ('active', 'active'),
        ('inactive', 'inactive')
        ), initial='all')
    mine = forms.BooleanField(required=False, label='Mine only', initial=False)


class WidgetsForm(forms.Form):
    date = forms.DateField(widget=BootstrapDateInput)


class FormSetInlineForm(forms.Form):
    foo = forms.CharField()
    bar = forms.CharField()

development/django_test_project/mysite/contact/forms.py
from django import forms

class ContactForm(forms.Form):
	subject = forms.CharField(max_length=100)
	email = forms.EmailField(required=False, label='Your e-mail address')
	message = forms.CharField(widget=forms.Textarea)
	
	def clean_message(self):
		message = self.cleaned_data['message']
		num_words = len(message.split())
		if num_words < 4:
			raise forms.ValidationError("Not enough words!")
		return message

development/django_test_project/django_mysite/demo_app/views.py
from django.contrib import messages
from django.forms.formsets import formset_factory
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

from bootstrap_toolkit.widgets import BootstrapUneditableInput

from forms import TestForm, TestModelForm, TestInlineForm, WidgetsForm, FormSetInlineForm

def example(request):
    return render_to_response('base.html.example')

def demo_form_with_template(request):
    layout = request.GET.get('layout')
    if not layout:
        layout = 'vertical'
    if request.method == 'POST':
        form = TestForm(request.POST)
        form.is_valid()
    else:
        form = TestForm()
    modelform = TestModelForm()
    return render_to_response('form_using_template.html', RequestContext(request, {
        'form': form,
        'layout': layout,
    }))

def demo_form(request):
    messages.success(request, 'I am a success message.')
    layout = request.GET.get('layout')
    if not layout:
        layout = 'vertical'
    if request.method == 'POST':
        form = TestForm(request.POST)
        form.is_valid()
    else:
        form = TestForm()
    form.fields['title'].widget = BootstrapUneditableInput()
    return render_to_response('form.html', RequestContext(request, {
        'form': form,
        'layout': layout,
    }))

def demo_form_inline(request):
    layout = request.GET.get('layout', '')
    if layout != 'search':
        layout = 'inline'
    form = TestInlineForm()
    return render_to_response('form_inline.html', RequestContext(request, {
        'form': form,
        'layout': layout,
    }))


def demo_formset(request):
    layout = request.GET.get('layout')
    if not layout:
        layout = 'inline'
    DemoFormSet = formset_factory(FormSetInlineForm)
    if request.method == 'POST':
        formset = DemoFormSet(request.POST, request.FILES)
        formset.is_valid()
    else:
        formset = DemoFormSet()
    return render_to_response('formset.html', RequestContext(request, {
        'formset': formset,
        'layout': layout,
    }))


def demo_tabs(request):
    layout = request.GET.get('layout')
    if not layout:
        layout = 'tabs'
    tabs = [
        {
            'link': "#",
            'title': 'Tab 1',
            },
        {
            'link': "#",
            'title': 'Tab 2',
            }
    ]
    return render_to_response('tabs.html', RequestContext(request, {
        'tabs': tabs,
        'layout': layout,
    }))


def demo_pagination(request):
    lines = []
    for i in range(10000):
        lines.append(u'Line %s' % (i + 1))
    paginator = Paginator(lines, 10)
    page = request.GET.get('page')
    try:
        show_lines = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        show_lines = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        show_lines = paginator.page(paginator.num_pages)
    return render_to_response('pagination.html', RequestContext(request, {
        'lines': show_lines,
    }))


def demo_widgets(request):
    layout = request.GET.get('layout', 'vertical')
    form = WidgetsForm()
    return render_to_response('form.html', RequestContext(request, {
        'form': form,
        'layout': layout,
    }))

development/django_test_project/mysite/contact/views.py
from django.shortcuts import render_to_response
from mysite.models import MyModel

def foobar_view(request, template_name):
	m_list = MyModel.objects.filter(is_new=True)
	return render_to_response(template_name, {'m_list': m_list})

def object_list(request, model):
	obj_list = model.objects.all()
	template_name = 'mysite/%s_list.html' % model.__name__.lower()
	return render_to_response(template_name, {'object_list': obj_list})

development/django_test_project/django_mysite/demo_app/templates/base.html
<!DOCTYPE html>
{% load bootstrap_toolkit %}
{% load url from future %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>django-bootstrap-toolkit = Bootstrap support for Django</title>
    <meta name="description" content="">
    <meta name="author" content="Dylan Verheul">
    <link href="{{ STATIC_URL }}b_css/bootstrap.bak.css" rel="stylesheet">
    <style type="text/css">
        body {
            padding-top: 60px;
        }
    </style>
    <!--[if lt IE 9]>
    <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    {% block extra_head %}{% endblock %}
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">django-bootstrap-toolkit</a>
            <div class="nav-collapse collapse">
            <ul class="nav">
                <li><a href="{% url 'demo_app:home' %}" class="">Home</a></li>
                <li><a href="{% url 'demo_app:demo_form' %}">Form</a></li>
                <li><a href="{% url 'demo_app:demo_formset' %}">Formset</a></li>
                <li><a href="{% url 'demo_app:demo_tabs' %}">Tabs &amp; Pills</a></li>
                <li><a href="{% url 'demo_app:demo_pagination' %}">Pagination</a></li>
                <li><a href="{% url 'demo_app:buttons' %}">Buttons</a></li>
                <li><a href="{% url 'demo_app:contact' %}">Contact</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Forms<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{% url 'demo_app:demo_form' %}?layout=vertical">Vertical</a></li>
                        <li><a href="{% url 'demo_app:demo_form' %}?layout=horizontal">Horizontal</a></li>
                        <li><a href="{% url 'demo_app:demo_form_inline' %}?layout=inline">Inline</a></li>
                        <li><a href="{% url 'demo_app:demo_form_inline' %}?layout=search">Search</a></li>
                        <li><a href="{% url 'demo_app:demo_form_with_template' %}?layout=horizontal">Using template</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="#">Action</a></li>
                  <li><a href="#">Another action</a></li>
                  <li><a href="#">Something else here</a></li>
                  <li class="divider"></li>
                  <li class="nav-header">Nav header</li>
                  <li><a href="#">Separated link</a></li>
                  <li><a href="#">One more separated link</a></li>
                </ul>
              </li>
            </ul>
        </div>
        </div>
    </div>
</div>



<div class="container">


    <p><hr></p>

    {% block content %}Empty page{% endblock %}
    
    <footer class="row">
        <div class="span6">
            <p>This is <a href="https://github.com/dyve/django-bootstrap-toolkit">django-bootstrap-toolkit</a></p>
        </div>
        <div class="span6" style="text-align:right">
            <p>
                &copy; <a href="http://twitter.com/dyve">Dylan Verheul</a> 2012
                |
                <a href="https://raw.github.com/dyve/django-bootstrap-toolkit/master/LICENSE">license</a>
            </p>
        </div>
    </footer>

</div> <!-- container -->

    <script src="{{ STATIC_URL }}b_js/jquery.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-transition.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-alert.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-modal.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-dropdown.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-scrollspy.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-tab.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-tooltip.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-popover.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-button.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-collapse.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-carousel.js"></script>
    <script src="{{ STATIC_URL }}b_js/bootstrap-typeahead.js"></script>

</body>
</html>

development/django_test_project/django_mysite/demo_app/templates/buttons.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

    <h1>Buttons</h1>

    {% bootstrap_button 'test' icon='info-sign' url='wakka' %}

    {% bootstrap_button 'test' icon='info-sign' url='wakka' size='mini' %}

    {% bootstrap_icon "info-sign" %}

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/contact.html
{% extends "base.html" %}

{% block content %}

    <p>Follow me on Twitter: <a href="http://twitter.com/dyve">@dyve</a></p>

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/form.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block extra_head %}
    {{ form.media }}
{% endblock %}

{% block content %}

    <h1>This is a <em>{{ layout }}</em> Django form, bootstrapped</h1>
    
    <p>&nbsp;</p>
        
    <form class="form-{{ layout }}" action="" method="post">
        {% csrf_token %}
        {{ form|as_bootstrap:layout }}
        {% if layout == "horizontal" %}
            <p class="form-actions">
                <input type="submit" value="Submit" class="btn btn-primary">
            </p>
        {% else %}
            <input type="submit" value="Submit" class="btn btn-primary">
        {% endif %}
    </form>

    <p>Submit the form to see error messages styled into it.</p>

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/form_inline.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

<h1>This is form layout is {{ layout }}</h1>

<p>&nbsp;</p>

<form class="form-{{ layout }}" action="" method="post">

    {% csrf_token %}

    {{ form|as_bootstrap:layout }}

    <input type="submit" class="text btn btn-primary">

</form>

<p>Submit the form to see error messages styled into it.</p>

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/form_using_template.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

    <h1>This form uses templates</h1>
    
    <p>The disabled field gets a $ appended using a template.</p>
    
    <p>&nbsp;</p>
        
    <form class="form-{{ layout }}" action="" method="post">
        {% csrf_token %}

        {% for field in form %}
            {% if field.name == 'disabled' %}
                {% include "bootstrap_toolkit/field.html" with append='$' %}
            {% else %}
                {% if field.name != 'color' %}
                    {% include "bootstrap_toolkit/field.html" %}
                {% endif %}
            {% endif %}
        {% endfor %}

        {% bootstrap_field form.color layout=layout %}

        {% if layout == "horizontal" %}
            <p class="form-actions">
                <input type="submit" value="Submit" class="btn btn-primary">
            </p>
        {% else %}
            <input type="submit" value="Submit" class="btn btn-primary">
        {% endif %}

    </form>

    <p>Submit the form to see error messages styled into it.</p>

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/formset.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block extra_head %}
    {{ formset.media }}
{% endblock %}

{% block content %}

    <h1>This is a <em>{{ layout }}</em> Django formset, bootstrapped</h1>

    <p>&nbsp;</p>

    <form class="form-{{ layout }}" action="" method="post">
        {% csrf_token %}

        {% bootstrap_formset formset=formset layout=layout %}

        {% if layout == "horizontal" %}
            <p class="form-actions">
                <input type="submit" value="Submit" class="btn btn-primary">
            </p>
        {% else %}
            <input type="submit" value="Submit" class="btn btn-primary">
        {% endif %}
    </form>

    <p>Submit the form to see error messages styled into it.</p>

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="well">
        <h1>Django, meet Bootstrap!</h1>
        <p>The django-bootstrap-toolkit application allows for an easy integration of Django and Bootstrap.</p>
        <p><a class="btn btn-primary" href="https://github.com/dyve/django-bootstrap-toolkit/">Check it out on GitHub &raquo;</a></p>
    </div>

    <div class="row">
        <div class="span4">
            <h2>Django</h2>

            <p>Django is the excellent Python web framework that makes a programmer's life less repetitive.</p>

            <p><a class="btn" href="http://www.djangoproject.com">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>Bootstrap</h2>

            <p>Bootstrap is a beautiful CSS framework with an optional JavaScript add-on.</p>

            <p><a class="btn" href="http://twitter.github.com/bootstrap/">View details &raquo;</a></p>
        </div>
        <div class="span4">
            <h2>django-bootstrap-toolkit</h2>

            <p>Is just a simple hustle to get two kinds of awesome together.</p>

            <p><a class="btn" href="https://github.com/dyve/django-bootstrap-toolkit/">View details &raquo;</a></p>
        </div>
    </div>

    <p>A big thanks to all the people that worked on Django and Bootstrap.</p>

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/pagination.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

    <h1>Pagination</h1>

    <table class="table">
        {% for line in lines %}
            <tr>
                <td>{{ line }}</td>
            </tr>
        {% endfor %}
    </table>

    {{ lines|pagination }}

    <hr>

    {% bootstrap_pagination lines url="/pagination?page=1&flop=flip" extra="q=foo" size="mini" align="right" %}

    {% bootstrap_pagination lines url="/pagination?page=1" align="center" size="large" %}

{% endblock %}

development/django_test_project/django_mysite/demo_app/templates/tabs.html
{% extends "base.html" %}

{% load bootstrap_toolkit %}

{% block content %}

    <h1>Tabs and Pills</h1>

    <h2>Tabs</h2>
    {% include "bootstrap_toolkit/tabs.html" %}

    <h2>Pills</h2>
    {% include "bootstrap_toolkit/pills.html" %}

{% endblock %}